name: Auth_Api_Sofbank

on:
  push:
    branches: [ "feat/jhuerfano/#0001_SonarQube" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  packages: write

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: gradle clean build jacocoTestReport

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/
            src/

  Analysis:
    runs-on: ubuntu-latest
    needs: Build
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dsonar.projectKey=julianest_auth_api
            -Dsonar.organization=julianest
            -Dsonar.sources=src
            -Dsonar.java.binaries=build/classes/java/main
            -Dsonar.java.source=17
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
            -Dsonar.java.libraries=build/libs/*.jar


  Publish:
    runs-on: ubuntu-latest
    needs: [Build, Analysis]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t auth_api -f Containerfile .

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag auth-api ghcr.io/${{ github.repository_owner }}/auth-api:v1.0.0

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner }}/auth-api:v1.0.0